spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

kafka:
  bootstrap_servers: localhost:19092,localhost:29092,localhost:39092

logging:
    level:
      org.apache.kafka.clients.admin.AdminClientConfig: WARN
      org.apache.kafka.clients.producer.ProducerConfig: WARN
