services:
  postgres:
    container_name: postgres
    image: postgres:13.5-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      # - ./volume/pgdata:/var/lib/postgresql/data
      - ./kubernetes/init/pg.sql:/docker-entrypoint-initdb.d/pg.sql
    command: [ "postgres", "-c", "wal_level=logical" ]