services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION}
    volumes:
      - "./volume/zookeeper/data:/data"
      - "./volume/zookeeper/logs:/datalog"
    ports:
      - "2181:2181"
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181 
      ZOOKEEPER_TIME_TICK: 2000
    networks:
      - kafka-zookeeper

  kafka0:
    container_name: kafka0
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 2
    #   KAFKA_LOG_DIRS: /data/kafka
    # volumes:
    #   - ./volume/kafka0_data:/data/kafka/
    depends_on:
      - zookeeper
    networks:
      - kafka-zookeeper

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    restart: on-failure
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 2
    #   KAFKA_LOG_DIRS: /data/kafka
    # volumes:
    #   - ./volume/kafka1_data:/data/kafka/
    depends_on:
      - zookeeper
    networks:
      - kafka-zookeeper

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    restart: on-failure
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 2
    #   KAFKA_LOG_DIRS: /data/kafka
    # volumes:
    #   - ./volume/kafka2_data:/data/kafka/
    depends_on:
      - zookeeper
    networks:
      - kafka-zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "localhost"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka0:9092,kafka1:9093,kafka2:9094"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_READONLY: "false"
    depends_on:
      - kafka0
      - kafka1
      - kafka2
    networks:
      - kafka-zookeeper

networks:
  kafka-zookeeper:
    name: kafka-zookeeper