
services:
  app1:
    container_name: app1
    build: 
      context: ./kafka-tester
      dockerfile: Dockerfile
    ports: [ "8080:8080" ]
    environment:
      SERVER_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      SCHEMA_REGISTRY: http://schema-registry:8081
    networks:
      - ppojin

  app2:
    container_name: app2
    build: 
      context: ./kafka-tester
      dockerfile: Dockerfile
    ports: [ "8082:8080" ]
    environment:
      SERVER_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      SCHEMA_REGISTRY: http://schema-registry:8081
    networks:
      - ppojin

networks:
  ppojin:
    name: ppojin
