apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
spec:
  ports:
    - port: 8080
      name: broker
      protocol: TCP
      targetPort: 8080
  selector:
    app: kafka-ui

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  containers:
  - name: app
    image: provectuslabs/kafka-ui:master
    env:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "local"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka-cp-kafka-0.kafka-cp-kafka-headless.default:9092,kafka-cp-kafka-1.kafka-cp-kafka-headless.default:9092,kafka-cp-kafka-2.kafka-cp-kafka-headless.default:9092"
    - name: KAFKA_CLUSTERS_0_ZOOKEEPER
      value: "kafka-cp-zookeeper-0:2181"
    - name: KAFKA_CLUSTERS_0_READONLY
      value: "false"