apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  ports:
    - port: 5432
      name: broker
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-entrypoint
data:
  pg.sql: |
    CREATE SCHEMA item;

    CREATE SEQUENCE stock_id_seq;
    CREATE TABLE item.stock (
      id integer NOT NULL DEFAULT nextval('stock_id_seq'),
      name varchar,
      stock integer
    );

    insert into item.stock (name, stock) values ('Home run ball', 100);
    insert into item.stock (name, stock) values ('Pepsi', 100);
    insert into item.stock (name, stock) values ('Banana', 100);
    insert into item.stock (name, stock) values ('Home run ball', 100);
    insert into item.stock (name, stock) values ('Neoguri', 100);

---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: app
    image: postgres:14.5
    # command:
    # - postgres
    # - -c
    # - wal_level=logical
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    volumeMounts:
    - name: config-volume
      mountPath: /docker-entrypoint-initdb.d
  volumes:
  - name: config-volume
    configMap:
      name: pg-entrypoint
      items:
      - key: pg.sql
        path: pg.sql
