### Json order
POST http://localhost:8080/v0/order
Content-Type: application/json

{
  "messages": [
    {"userId": "a", "productId": "Home run ball", "count": 3},
    {"userId": "b", "productId": "Pepsi", "count": 5},
    {"userId": "c", "productId": "Banana", "count": 3},
    {"userId": "d", "productId": "Neoguri", "count": 10}
  ]
}

### Avro order
POST http://localhost:8080/v1/order
Content-Type: application/json

{
  "messages": [
    {"userId": "a", "productId": "Home run ball", "count": 3},
    {"userId": "b", "productId": "Pepsi", "count": 10},
    {"userId": "c", "productId": "Banana", "count": 3},
    {"userId": "d", "productId": "Neoguri", "count": 10},
    {"userId": "e", "productId": "cass", "count": 10}
  ]
}
