## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  enabled: true
  servers: 1
  image: confluentinc/cp-zookeeper
  imageTag: 7.4.1
  imagePullSecrets:
  #  - name: "regcred"
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    dataDirSize: 128Mi
    dataLogDirSize: 100Mi
    
  securityContext: 
    runAsUser: 0

  resources:
   limits:
    cpu: 500m
    memory: 600Mi
   requests:
    cpu: 100m
    memory: 256Mi
  prometheus:
    jmx:
      enabled: false

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true
  brokers: 3
  image: confluentinc/cp-kafka
  imageTag: 7.4.1
  imagePullSecrets:
  #  - name: "regcred"
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    # storageClass: ""
    size: 100Mi
    disksPerBroker: 1
  resources:
   limits:
    cpu: 500m
    memory: 600Mi
   requests:
    cpu: 100m
    memory: 256Mi
  securityContext: 
    runAsUser: 0
  prometheus:
    jmx:
      enabled: false
  configurationOverrides:
    "offsets.topic.replication.factor": "3"
    "default.replication.factor": 3
    "min.insync.replicas": 2
    "auto.create.topics.enable": false
    "advertised.listeners": EXTERNAL://localhost:$((19092 + ${KAFKA_BROKER_ID}))
    "listener.security.protocol.map": PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    "metric.reporters": ""
    "confluent.metrics.reporter.bootstrap.servers": ""
  nodeport:
    enabled: false

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: false
  image: confluentinc/cp-schema-registry
  imageTag: 7.4.1
  imagePullSecrets:
  heapOptions: "-Xms256M -Xmx256M"
  resources: 
   limits:
    cpu: 500m
    memory: 128Mi
   requests:
    cpu: 500m
    memory: 128Mi

cp-kafka-rest:
  enabled: false

cp-kafka-connect:
  enabled: false

cp-ksql-server:
  enabled: false

cp-control-center:
  enabled: false