### create consumer
POST http://localhost:8080/consumer
Content-Type: application/json

{
  "topicName": "thing1"
}

### list consumer
GET http://localhost:8080/consumer

### get consumer
GET http://localhost:8080/consumer/thing1

### delete consumer
DELETE http://localhost:8080/consumer/thing1

### produce message
POST http://localhost:8080/producer/MR_MP
Content-Type: application/json

[
  {
    "key": "a",
    "contents": "a"
  },
  {
    "key": "b",
    "contents": "b"
  },
  {
    "key": "c",
    "contents": "c"
  },
  {
    "key": "d",
    "contents": "d"
  },
  {
    "key": "e",
    "contents": "e"
  }
]